language: elixir
elixir:
  - 1.9.0
otp_release:
  - 22.0
services:
  - postgresql
env:
  - MIX_ENV=test
before_script:
  - mix deps.get
  - nvm install 6.2 && nvm use 6.2
  - mix do ecto.create, ecto.migrate
script:
  - mix test
notifications:
  email: false
